import math
from SpawnLocation import SpawnLocation
MAX_TURN = 220


MAP_WIDTH = 17630
MAP_HEIGHT = 9000
MAP_LIMIT = 800

BASE_ATTRACTION_RADIUS = 5000
BASE_VIEW_RADIUS = 6000
BASE_RADIUS = 300

HERO_MOVE_SPEED = 800
HEROES_PER_PLAYER = 3
HERO_VIEW_RADIUS = 2200
HERO_ATTACK_RANGE = 800
HERO_ATTACK_DAMAGE = 2

MAX_MANA = -1
STARTING_MANA = 0
STARTING_BASE_HEALTH = 3

MOB_MOVE_SPEED = 400
MOB_SPAWN_LOCATIONS = [SpawnLocation(MAP_WIDTH / 2, -MAP_LIMIT + 1),
                       SpawnLocation(MAP_WIDTH / 2 + 4000, -MAP_LIMIT + 1)]
MOB_SPAWN_MAX_DIRECTION_DELTA = 5 * math.pi / 12
MOB_SPAWN_RATE = 5
MOB_STARTING_MAX_ENERGY = 10
MOB_GROWTH_MAX_ENERGY = 0.5

SPELL_WIND_COST = 10
SPELL_CONTROL_COST = 10
SPELL_PROTECT_COST = 10
SPELL_PROTECT_DURATION = 12
SPELL_WIND_DISTANCE = 2200
SPELL_WIND_RADIUS = 1280
ENABLE_FOG = True
ENABLE_WIND = True
ENABLE_CONTROL = True
ENABLE_SHIELD = True
ENABLE_TIE_BREAK = True
